### ISSUE TITLE
Tidak ada status berhasil atau gagal terkirim

### ISSUE THREAD

**Issue by tamboto2000** [widhisec/sms-gratis#1]
Saat eksekusi tidak ada pesan terkirim atau gagal terkirim, pesan juga tidak terkirim

Run on: Ubuntu 20.04 WSL, Windows 10 Home Version 20H2
![Screenshot (102)](https://user-images.githubusercontent.com/23492779/104492779-b7e59100-5606-11eb-8368-0b9efc15e8a1.png)

**Comment by widhisec** [comment]
> Saat eksekusi tidak ada pesan terkirim atau gagal terkirim, pesan juga tidak terkirim
> 
> Run on: Ubuntu 20.04 WSL, Windows 10 Home Version 20H2
> ![Screenshot (102)](https://user-images.githubusercontent.com/23492779/104492779-b7e59100-5606-11eb-8368-0b9efc15e8a1.png)

Iya itu subdomain udah berubah gan makanya gak bisa
